"""Pydantic models shared across the pipeline."""
from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field

Confidence = Literal["low", "medium", "high"]

# Who would realistically pose the question after a pharma earnings release.
Asker = Literal["journalist", "analyst"]


class ContentKind(str, Enum):
    PRINTED = "printed"
    HANDWRITTEN = "handwritten"
    TABLE = "table"
    MIXED = "mixed"


class PageResult(BaseModel):
    """Parsed output for a single PDF page."""
    page_number: int
    markdown: str = ""
    backend: str = ""
    kind: ContentKind = ContentKind.PRINTED
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    has_handwriting: bool = False
    notes: list[str] = Field(default_factory=list)


class ParseResult(BaseModel):
    """Full-document parse output."""
    source_filename: str
    page_count: int
    backend_summary: dict[str, int] = Field(default_factory=dict)
    pages: list[PageResult] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    @property
    def markdown(self) -> str:
        parts = [
            f"\n\n<!-- page {p.page_number} ({p.backend}) -->\n{p.markdown}"
            for p in self.pages
        ]
        return "".join(parts).strip()


class QAItem(BaseModel):
    question: str
    answer: str
    # Who would ask this — a beat journalist (WSJ/NYT/FT/STAT) or a sell-/buy-side
    # analyst. Drives tone and framing of the question.
    asker: Asker = "analyst"
    # Why this question is being asked and where it comes from. This is mandatory
    # context for the CFO: what in the filing (or in the competitive landscape)
    # prompts it. Should reference the cited source page(s).
    reasoning: str = ""
    # Peer/competitor angle — how comparable pharma companies frame the same issue
    # (e.g. an analyst benchmarking pipeline or margins against larger peers).
    # Null when the question is not a peer comparison.
    peer_context: str | None = None
    category: str = "general"
    confidence: Confidence = "medium"
    source_pages: list[int] = Field(default_factory=list)
    caveat: str | None = None


class QADocument(BaseModel):
    company: str | None = None
    period: str | None = None
    title: str = "Pharma Analyst & Journalist Q&A Brief"
    generated_from: str = ""
    items: list[QAItem] = Field(default_factory=list)
    disclaimer: str = (
        "Generated by AI from the source document. Questions reflect this filing "
        "and the pharma sector context; competitor figures are illustrative. "
        "Verify all numbers against the official filing before external use."
    )


class ProcessResponse(BaseModel):
    parse: ParseResult
    qa: QADocument | None = None
    timings_ms: dict[str, float] = Field(default_factory=dict)
    meta: dict[str, Any] = Field(default_factory=dict)
