"""Pydantic models shared across the pipeline."""
from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

Confidence = Literal["low", "medium", "high"]

# Who would realistically pose the question after a pharma earnings release.
Asker = Literal["journalist", "analyst"]


class ContentKind(str, Enum):
    PRINTED = "printed"
    HANDWRITTEN = "handwritten"
    TABLE = "table"
    MIXED = "mixed"


class PageResult(BaseModel):
    """Parsed output for a single PDF page."""
    page_number: int
    markdown: str = ""
    backend: str = ""
    kind: ContentKind = ContentKind.PRINTED
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    has_handwriting: bool = False
    notes: list[str] = Field(default_factory=list)


class ParseResult(BaseModel):
    """Full-document parse output."""
    source_filename: str
    page_count: int
    backend_summary: dict[str, int] = Field(default_factory=dict)
    pages: list[PageResult] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    @property
    def markdown(self) -> str:
        parts = [
            f"\n\n<!-- page {p.page_number} ({p.backend}) -->\n{p.markdown}"
            for p in self.pages
        ]
        return "".join(parts).strip()


class PeerCitation(BaseModel):
    """A real, web-sourced reference showing where a comparable pharma company
    faced a similar question (and, when the source says so, how they answered).

    Populated by :class:`app.qa.peer_retrieval.PeerCitationEnricher` from
    Anthropic's web-search tool — every field is grounded in a live search
    result, never invented. ``url``/``title``/``quote`` come straight from the
    web-search citation; ``peer``/``venue`` are best-effort attribution.
    """
    url: str
    title: str = ""
    # The comparable company the source is about (e.g. "Pfizer"), when identifiable.
    peer: str | None = None
    # Where the question surfaced for the peer — "earnings call", "investor day",
    # "10-K", "press", etc. — when identifiable from the source.
    venue: str | None = None
    # The cited snippet from the source that backs the reference.
    quote: str = ""


class QAItem(BaseModel):
    question: str
    answer: str
    # Who would ask this — a beat journalist (WSJ/NYT/FT/STAT) or a sell-/buy-side
    # analyst. Drives tone and framing of the question.
    asker: Asker = "analyst"
    # Why this question is being asked and where it comes from. This is mandatory
    # context for the CFO: what in the filing (or in the competitive landscape)
    # prompts it. Should reference the cited source page(s).
    reasoning: str = ""
    # Peer/competitor angle — how comparable pharma companies frame the same issue
    # (e.g. an analyst benchmarking pipeline or margins against larger peers).
    # Null when the question is not a peer comparison.
    peer_context: str | None = None
    # Web-grounded enrichment for peer-comparison questions (filled in a second
    # pass, only when web search is enabled and the question has peer_context):
    #   * peer_answer — a citation-backed summary of where/whether a comparable
    #     company faced this question and how they answered it; None when the
    #     search found nothing usable ("else no problem").
    #   * peer_citations — the real sources behind peer_answer.
    peer_answer: str | None = None
    peer_citations: list[PeerCitation] = Field(default_factory=list)
    category: str = "general"
    confidence: Confidence = "medium"
    source_pages: list[int] = Field(default_factory=list)
    caveat: str | None = None

    @model_validator(mode="after")
    def _grounded_or_nothing(self) -> "QAItem":
        """Enforce the grounded-or-nothing contract for peer enrichment.

        A web-grounded ``peer_answer`` may exist ONLY when backed by at least one
        real ``peer_citation``. If an answer arrives without citations (a buggy
        enrichment path, a hand-built item, or malformed deserialized data), drop
        it rather than surface an unsourced peer claim as if it were sourced.
        This makes "we either have citations or we don't" a structural invariant
        of the model itself, not just a convention in one code path.
        """
        if self.peer_answer and not self.peer_citations:
            self.peer_answer = None
        return self


class QADocument(BaseModel):
    company: str | None = None
    period: str | None = None
    title: str = "Pharma Analyst & Journalist Q&A Brief"
    generated_from: str = ""
    items: list[QAItem] = Field(default_factory=list)
    disclaimer: str = (
        "Generated by AI from the source document. Questions reflect this filing "
        "and the pharma sector context; competitor figures are illustrative. "
        "Verify all numbers against the official filing before external use."
    )


class ProcessResponse(BaseModel):
    parse: ParseResult
    qa: QADocument | None = None
    timings_ms: dict[str, float] = Field(default_factory=dict)
    meta: dict[str, Any] = Field(default_factory=dict)
